# Generated by Django 5.0 on 2023-12-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('query', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
