# Generated by Django 5.0 on 2024-01-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=122)),
                ('p_category', models.CharField(max_length=122)),
                ('p_date', models.DateField()),
            ],
        ),
    ]
