# Generated by Django 5.0 on 2024-01-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_img',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
