# Generated by Django 5.0 on 2024-02-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='item_price',
            field=models.FloatField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
