# Generated by Django 5.0 on 2024-02-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_purchasehistory_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='item_cat',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
