# Generated by Django 5.0 on 2024-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_purchasehistory_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='item_img',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
    ]
