# Generated by Django 5.0 on 2024-03-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_desc',
            field=models.CharField(default=0, max_length=122),
            preserve_default=False,
        ),
    ]
