# Generated by Django 5.0 on 2024-04-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_product_clothing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='item_clothing_id',
            field=models.IntegerField(null=True),
        ),
    ]
